server:
  port: 8083
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      add-type-info: false
resilience4j:
  circuitbreaker:
    instances:
      paymentGateway:
        slidingWindowSize: 5
        failureRateThreshold: 60
        waitDurationInOpenState: 15s
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
